#!/usr/bin/env bash
set -euo pipefail

# ============================================================================
# scripts/linux/clean.sh
#
# Removes Qt/qmake autogenerated build files for this project.
#
# Usage:
#     scripts/linux/clean.sh
#
# It always cleans the project this script lives in, whatever the current
# directory is, and it never leaves the project folder.
#
# This script does NOT delete:
#     *.cpp
#     *.h
#     *.pro
#     *.txt
#     *.md
#     docs/
#     scripts/
#     peers.txt or any other collector output
# ============================================================================

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
project_root="$(cd -- "$script_dir/../.." && pwd)"

if [ ! -f "$project_root/libtorrent_peer_collector_qt.pro" ]; then
	echo "ERROR: not a libtorrent_peer_collector project folder: $project_root" >&2
	exit 1
fi

cd -- "$project_root"

echo
echo "Cleaning Qt/qmake autogenerated files in:"
pwd
echo

# ---- Qt Creator / qmake build folders ----
# deploy is what scripts/linux/deploy.sh and scripts/windows/deploy.bat write
# when given no other destination. It is cleaned here too so a tree shared
# between the two ends up in the same state either way.
for d in build build-* deploy Desktop_Qt_* debug release .qtc_clangd; do
	if [ -e "$d" ]; then
		echo "Removing folder: $d"
		rm -rf -- "$d"
	fi
done

# ---- qmake generated files ----
for f in \
	Makefile \
	Makefile.Debug \
	Makefile.Release \
	.qmake.stash \
	moc_predefs.h \
	object_script.*.Debug \
	object_script.*.Release
do
	for match in $f; do
		if [ -e "$match" ]; then
			echo "Deleting file: $match"
			rm -f -- "$match"
		fi
	done
done

# ---- Qt generated source/header files ----
rm -f -- moc_*.cpp qrc_*.cpp ui_*.h *.moc

# ---- Compiler/linker generated files in source folder ----
rm -f -- *.o *.obj *.a *.so *.dll.a

# Do not delete the Linux executable automatically because it may have the same
# name as the project and you may want to keep it. Uncomment if needed:
# rm -f -- libtorrent_peer_collector_qt

echo
echo "Clean completed."
echo
