@echo off
setlocal

rem ============================================================================
rem scripts\windows\clean.bat
rem
rem Removes Qt/qmake autogenerated build files for this project.
rem
rem Usage:
rem     scripts\windows\clean.bat
rem
rem It always cleans the project this script lives in, whatever the current
rem directory is, and it never leaves the project folder.
rem
rem This script does NOT delete:
rem     *.cpp
rem     *.h
rem     *.pro
rem     *.txt
rem     *.md
rem     docs\
rem     scripts\
rem     peers.txt or any other collector output
rem ============================================================================

pushd "%~dp0..\.."
if errorlevel 1 (
    echo ERROR: failed to locate the project folder.
    exit /b 1
)
set "PROJECT_ROOT=%CD%"

if not exist "%PROJECT_ROOT%\libtorrent_peer_collector_qt.pro" (
    echo ERROR: not a libtorrent_peer_collector project folder:
    echo "%PROJECT_ROOT%"
    popd
    exit /b 1
)

echo.
echo Cleaning Qt/qmake autogenerated files in:
echo %PROJECT_ROOT%
echo.

rem ---- Qt Creator / qmake build folders ----
if exist "build" (
    echo Removing folder: build
    rmdir /s /q "build"
)

for /d %%D in (build-*) do (
    if exist "%%D" (
        echo Removing folder: %%D
        rmdir /s /q "%%D"
    )
)

rem The folder deploy.bat writes. It only ever holds copies of the EXE and of
rem Qt's and libtorrent's DLLs, so there is nothing in it that cannot be
rem rebuilt.
if exist "deploy" (
    echo Removing folder: deploy
    rmdir /s /q "deploy"
)

for /d %%D in (Desktop_Qt_*) do (
    if exist "%%D" (
        echo Removing folder: %%D
        rmdir /s /q "%%D"
    )
)

if exist "debug" (
    echo Removing folder: debug
    rmdir /s /q "debug"
)

if exist "release" (
    echo Removing folder: release
    rmdir /s /q "release"
)

if exist ".qtc_clangd" (
    echo Removing folder: .qtc_clangd
    rmdir /s /q ".qtc_clangd"
)

rem ---- qmake generated files ----
for %%F in (
    Makefile
    Makefile.Debug
    Makefile.Release
    .qmake.stash
    moc_predefs.h
    object_script.*.Debug
    object_script.*.Release
) do (
    if exist "%%F" (
        echo Deleting file: %%F
        del /f /q "%%F"
    )
)

rem ---- Qt generated source/header files ----
del /f /q moc_*.cpp 2>nul
del /f /q qrc_*.cpp 2>nul
del /f /q ui_*.h 2>nul
del /f /q *.moc 2>nul

rem ---- Compiler/linker generated files in source folder ----
del /f /q *.o 2>nul
del /f /q *.obj 2>nul
del /f /q *.a 2>nul
del /f /q *.lib 2>nul
del /f /q *.dll.a 2>nul
del /f /q *.exe 2>nul

popd

echo.
echo Clean completed.
echo.

echo %cmdcmdline% | find /i "%~nx0" >nul
if not errorlevel 1 pause

rem The find above leaves errorlevel 1 when the script was not double
rem clicked, so success is reported explicitly for a caller such as
rem rebuild.bat.
endlocal
exit /b 0
